export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCTS: 'REMOVE_SELECTED_PRODUCTS',
    SET_CATEGORY: 'SET_CATEGORY',
    RESET_CATEGORY: 'RESET_CATEGORY',
    SET_CART: 'SET_CART',
    INC_CART_ITEM_QUANTITY: 'INC_CART_ITEM_QUANTITY',
    DEC_CART_ITEM_QUANTITY: 'DEC_CART_ITEM_QUANTITY',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    ANIMATE_CART_LINK: 'ANIMATE_CART_LINK',
}